### ISSUE TITLE
Discussion: Teach what the shebang line is?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/py-rse#339]
Or remove its [mention in style.Rmd](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-rse/style.Rmd#L179)?

**Comment by DamienIrving** [comment]
I left the shebang out of the python scripting lesson because from googling around it seemed that it doesn't work / needs to be slightly different depending on the operating system?

I'd be open to adding a call out box in the python scripting lesson to briefly discuss what the shebang is (in case people come across it elsewhere), but unless we can be sure that it will work on any operating system I don't think we should actually add it to our `countwords.py`, `collate.py` and `plotcounts.py` scripts.

**Comment by joelostblom** [comment]
My understanding is that it should be pretty portable nowadays and envs should be fine as long as `/usr/bin/env python` is used (https://docs.python.org/3/using/windows.html#shebang-lines), but I don't have extensive experience running this on different OSes. I agree with your idea of a mention.

**Comment by gvwilson** [comment]
I think we need to teach this - people are going to see it a lot when they start working with other people's scripts.

**Comment by joelostblom** [comment]
Good, I will PR when the current PRs have closed since there is a lot of new material under review currently. Also mentioned in #341

**Comment by joelostblom** [comment]
Decided on the meeting today that we will add back shebangs. @DamienIrving I can try this first in packaging and if it works well there, you can add it back to scripting?

**Comment by DamienIrving** [comment]
@joelostblom That sounds like a good plan :smile:
