### ISSUE TITLE
Discussion: How do we manage updates after the book is published?

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#499]
I'm assuming that once we've sent the final manuscript off to be published, we'll tag release v1.0.0 in GitHub.

What happens after that?

If readers of the book submit PRs or issues and changes are made to the book, are those changes immediately pushed to the web version of the book at https://merely-useful.github.io/py-rse/ like changes are now? Or do we wait until a bunch of changes come in and bundle them into a new release (e.g. v1.0.1) before pushing to the website? Or do we want the website to reflect exactly what is in the physical book and thus we wouldn't push any changes to the website until a new version of the physical book is published?

This question has implications for what we say in the book about people contributing / getting involved (e.g. in the Contributing appendix or Finale chapter).

**Comment by lwjohnst86** [comment]
I am in favour of tagging as v1.0.0 and then as things go, keep updating the website or encouraging others to contribute. Then we can decide (or the publishers) that enough changes have been made since the first release to update the physical book. But I think the website should be flexible to updates and changes.
